### ISSUE TITLE
Add typescript support

### ISSUE THREAD

**Issue by pedrodurek** [andrescalco/andrescalco-card#3]
Add typescript support

**Comment by andrescalco** [comment]
┏┓
┃┃╱╲ in
┃╱╱╲╲ this
╱╱╭╮╲╲house
▔▏┗┛▕▔ we
╱▔▔▔▔▔▔▔▔▔▔╲
say no to Typescript
╱╱┏┳┓╭╮┏┳┓ ╲╲
▔▏┗┻┛┃┃┗┻┛▕▔

**Comment by jstheoriginal** [comment]
Please add!!!
